### ISSUE TITLE
Assignment for Thursday, 9/10/2015

### ISSUE THREAD

**Issue by FeiWangMHC** [AmherstCollege/STAT495-Fei-Wang-public#1]
Do you know that it is Teachers' Day on Sept 10 in China? Best wishes to all the teachers around the world! Well, I should say that to my mom as well, haha! :dancer:

**Comment by akothapa** [comment]
That's so cool! Is it an official holiday/how is it celebrated in China?

**Comment by FeiWangMHC** [comment]
Yes, it's official. When I was in primary and secondary school, we had a half-day celebration (usually performances by students) and the other half free of class. For higher level students, however, we do not enjoy no-class holiday. Nevertheless, we usually give thank-you cards and gifts to our teachers as tokens of appreciation. :)

**Comment by tbsmith16** [comment]
That's very cool so your mom teaches?

**Comment by FeiWangMHC** [comment]
yap, my mom teaches Chinese. :)
